version: '3.8'

services:
 web1:
  build:
   context: .
  container_name: Node1
  ports:
  - 8000:5000
  - 8001:5005
  - 8002:5006
  volumes:
  - .\:/app
  environment:
  - DATABASE_FILENAME=test1.db
  - STATE=leader 
  - LEADER_ID=Node1
  - LEADER=1
  - PYTHONUNBUFFERED=1
  - NODEID=Node1
  - current_term=1
  - voted=1
  - SHUTDOWN_FLAG=0
  - ACTIVE_NODES=0

 web2:
  build:
   context: .
  container_name: Node2
  ports:
  - 5100:5000
  - 5101:5005
  - 5102:5006
  volumes:
  - .\:/app
  environment:
  - DATABASE_FILENAME=test2.db
  - STATE=follower
  - LEADER_ID=Node1 
  - LEADER=0
  - PYTHONUNBUFFERED=1
  - NODEID=Node2
  - current_term=1
  - voted=0
  - SHUTDOWN_FLAG=0
  - ACTIVE_NODES=0

 web3:
  build:
   context: .
  container_name: Node3
  ports:
  - 5200:5000
  - 5201:5005
  - 5202:5006
  volumes:
  - .\:/app
  environment:
  - DATABASE_FILENAME=test3.db
  - STATE=follower 
  - LEADER_ID=Node1
  - LEADER=0
  - PYTHONUNBUFFERED=1
  - NODEID=Node3
  - current_term=1
  - voted=0
  - SHUTDOWN_FLAG=0
  - ACTIVE_NODES=0

 web4:
  build:
   context: .
  container_name: Node4
  ports:
  - 5400:5000
  - 5401:5005
  - 5402:5555
  volumes:
  - ./:/app
  environment:
  - DATABASE_FILENAME=test4.db
  - STATE=follower 
  - LEADER_ID=Node1
  - LEADER=0
  - PYTHONUNBUFFERED=1
  - NODEID=Node4
  - current_term=1
  - voted=0
  - SHUTDOWN_FLAG=0
  - ACTIVE_NODES=0

 web5:
  build:
   context: .
  container_name: Node5
  ports:
  - 5500:5000
  - 5501:5005
  - 5502:5555
  volumes:
  - ./:/app
  environment:
  - DATABASE_FILENAME=test5.db
  - STATE=follower 
  - LEADER_ID=Node1
  - LEADER=0
  - PYTHONUNBUFFERED=1
  - NODEID=Node5
  - current_term=1
  - voted=0
  - SHUTDOWN_FLAG=0
  - ACTIVE_NODES=0

 controller:
  container_name: Controller
  build: Controller/.
  stdin_open: true

