version: '3.8'

services:
 web1:
  build:
   context: .
  ports:
  - 8000:5000
  volumes:
  - .\:/app
  networks:
  - dist-trial
  environment:
  - DATABASE_FILENAME="test1.db"
  - LEADER=True
  container_name: leader

 web2:
  build:
   context: .
  ports:
  - 5100:5000
  volumes:
  - .\:/app
  networks:
  - dist-trial
  environment:
  - DATABASE_FILENAME="test2.db"
  - LEADER=False
  container_name: follower_1

 web3:
  build:
   context: .
  ports:
  - 5101:5000
  volumes:
  - .\:/app
  networks:
  - dist-trial
  environment:
  - DATABASE_FILENAME="test3.db"
  - LEADER=False
  container_name: follower_2
  
networks:
  dist-trial: